apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flask-app-route
  namespace: default
spec:
  parentRefs:
    - name: main-gateway
      sectionName: web-main # Привязываем строго к HTTP/HTTPS для основного домена
  hostnames:
    - "reshort.duckdns.org"
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: flask-service # ИСПРАВЛЕНО: Было flask-app-service
          port: 5000