spec:
  hostnames:
  - reshort.duckdns.org
  parentRefs:
  - name: main-gateway
    sectionName: web # Убедитесь, что это совпадает с вашим Gateway
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: flask-service # Убедитесь, что имя сервиса верно
      port: 5000