apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: main-gateway
  namespace: default
spec:
  gatewayClassName: traefik
  listeners:
    # 1. HTTP-слушатель (порт 80) — теперь он явно ждет твою доменную зону
    - name: web
      protocol: HTTP
      port: 80
      hostname: "*.duckdns.org" # <--- ДОБАВЛЕНО: Разрешает и reshort, и grafana, и роуты cert-manager
      allowedRoutes:
        namespaces:
          from: All

    # 2. HTTPS-слушатель для основного домена (порт 443)
    - name: websecure-main
      protocol: HTTPS
      port: 443
      hostname: "reshort.duckdns.org"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: flask-grafana-tls-secret

    # 3. HTTPS-слушатель для Графаны (порт 443)
    - name: websecure-grafana
      protocol: HTTPS
      port: 443
      hostname: "grafana.reshort.duckdns.org"
      allowedRoutes:
        namespaces:
          from: All
      tls:
        mode: Terminate
        certificateRefs:
          - name: flask-grafana-tls-secret