apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    additionalArguments:
      - "--providers.kubernetesgateway"
      - "--entryPoints.web.address=:8000"
      - "--entryPoints.websecure.address=:8443"