[webservers]
# IP-адрес твоего сервера в облаке
web-node-1 ansible_host=111.88.255.146

[webservers:vars]
# Под каким пользователем подключаться
ansible_user=ubuntu
# Путь к твоему приватному SSH-ключу на локальном компьютере
ansible_ssh_private_key_file=~/.ssh/id_ed25519_wsl
# Отключаем строгую проверку ключа хоста, чтобы скрипт не спотыкался при первом подключении
ansible_ssh_common_args='-o StrictHostKeyChecking=no'