---
- name: Подготовка сервера и установка Docker
  hosts: webservers
  become: yes

  tasks:
    - name: Создать директорию для GPG-ключей apt
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Скачать и добавить официальный GPG-ключ Docker
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        mode: '0644'

    - name: Добавить официальный репозиторий Docker в apt
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
        state: present
        filename: docker

    - name: Установить Docker Engine, CLI и Docker Compose
      ansible.builtin.apt:
        pkg:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Убедиться, что служба Docker запущена и добавлена в автозагрузку
      ansible.builtin.systemd:
        name: docker
        state: started
        enabled: yes

    # --- ДЕПЛОЙ ПРИЛОЖЕНИЯ ---
    - name: Создать рабочую папку для проекта на сервере
      ansible.builtin.file:
        path: /home/ubuntu/app
        state: directory
        mode: '0755'
        owner: ubuntu
        group: ubuntu

    - name: Скопировать файлы приложения и docker-compose на server
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: '0644'
      loop:
        - { src: '../docker-compose.yml', dest: '/home/ubuntu/app/docker-compose.yml' }
        - { src: '../app/', dest: '/home/ubuntu/app/app/' }

    - name: Собрать Docker-образы и запустить проект через Docker Compose
      ansible.builtin.shell:
        cmd: docker compose up -d --build
        chdir: /home/ubuntu/app