name: Flask K8s CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем свежий код из репозитория
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Логинимся в Docker Hub с помощью сохраненных секретов
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # 3. Собираем свежий Docker-образ и пушим его в Docker Hub
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: ./app
        file: ./app/Dockerfile
        push: true
        # Используем секрет или пишем напрямую, главное — точное совпадение с деплоем:
        tags: docker.io/rekiles/flask-app:latest

    # 4. Настраиваем SSH-ключ для подключения к нашей работающей Ubuntu
    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    # 5. Подключаемся к серверу и деплоим
    - name: Deploy to Kubernetes via SSH
      run: |
        ssh -i ~/.ssh/id_ed25519 ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
          cd ~/k8s-project
          git pull origin main
          
          # Создаем файл .env из секрета GitHub на сервере
          echo "${{ secrets.ENV_FILE }}" > .env
          
          # Генерируем или обновляем кубер-секрет из этого файла
          sudo kubectl create secret generic app-secrets --from-env-file=.env --dry-run=client -o yaml | sudo kubectl apply -f -
          rm .env # удаляем временный файл ради безопасности
          
          # Накатываем остальные манифесты
          sudo kubectl apply -f k8s/
          sudo kubectl rollout restart deployment flask-deployment
        EOF