name: GitOps Complete Pipeline (Terraform + Ansible)

on:
  push:
    branches: [ main ]

jobs:
  automation:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Create Yandex SA Key File
      run: |
        echo '${{ secrets.YC_SA_KEY }}' > terraform/key.json

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.15.5"
        terraform_wrapper: false # <--- ОТКЛЮЧАЕМ ОБЕРТКУ, чтобы вывод output был чистым текстом!

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="access_key=${{ secrets.YC_ACCESS_KEY }}" \
          -backend-config="secret_key=${{ secrets.YC_SECRET_KEY }}"
      working-directory: ./terraform

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var="cloud_id=${{ secrets.YC_CLOUD_ID }}" \
          -var="folder_id=${{ secrets.YC_FOLDER_ID }}" \
          -var="ssh_public_key=${{ secrets.SSH_PUBLIC_KEY }}"
      working-directory: ./terraform

    - name: Get Server IP
      id: get_ip
      run: |
        SERVER_IP=$(terraform output -raw external_ip | tr -d '\r\n[:space:]') # Дополнительно очищаем от скрытых символов переноса строки
        echo "server_ip=$SERVER_IP" >> $GITHUB_OUTPUT
      working-directory: ./terraform

    - name: Set up SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ steps.get_ip.outputs.server_ip }} >> ~/.ssh/known_hosts

    - name: Install Ansible
      run: |
        sudo apt-get update
        sudo apt-get install -y ansible

    - name: Create Ansible Inventory
      run: |
        echo "[webservers]" > ansible/inventory.ini
        echo "web-node-1 ansible_host=${{ steps.get_ip.outputs.server_ip }} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_ed25519" >> ansible/inventory.ini

    - name: Create .env file
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env

    - name: Run Ansible Playbook
      run: |
        cd ansible
        ansible-playbook -i inventory.ini playbook.yml